### ISSUE TITLE
Optionally throttle CPU usage or ffmpeg thread count

### ISSUE THREAD

**Issue by BernsteinA** [MediaBrowser/roku-bif#1]
**edit 2019/19/01** For what it's worth, and for future readers: I managed to set up cpu throttling for ffmpeg using cgroups.
In my case, I wanted to limit ffmpeg to 50% total cpu usage, without constraining the whole emby server docker container. I'm running DietPi on a Rock64, but I assume this would work with any debian or ubuntu linux machine.

1. `apt-get install cgroup-tools`
2. add the following to `/etc/cgconfig.conf` (2000000 / 1000000 = 100% of two CPUs):
```
group ffmpeg {
  cpu {
    cpu.cfs_quota_us = 2000000;
    cpu.cfs_period_us = 1000000;
  }
}
```
3. add the following to `/etc/cgrules.conf`:
```
*:ffmpeg    cpu    ffmpeg/
```
4. `cgconfigparser -l /etc/cgconfig.conf`
5. `cgrulesengd -vvv --logfile=/var/log/cgrulesengd.log`

I also set up a service to run the above two lines automatically. See here: https://askubuntu.com/a/848022

**Comment by BernsteinA** [comment]
@LukePulverenti I'm having trouble figuring out where `IMediaEncoder.ExtractVideoImagesOnInterval` is implemented

**Comment by LukePulverenti** [comment]
That is currently not open source, but to be honest, i would suggest waiting a few weeks on this. We are currently working on a new technique to extract the images, and in some cases it will be as much as 95% faster than the current way. If you follow the beta channel I would imagine we'll have this available within a few weeks. Thanks !

**Comment by BernsteinA** [comment]
Ah, thanks, I didn't realise there were closed-source parts.
You're referring to the beta channel of Emby Server?

**Comment by LukePulverenti** [comment]
Yes exactly, thanks.

**Comment by BernsteinA** [comment]
@LukePulverenti Am I correct in understanding that this plugin is dead and there's still no way to throttle the roku thumbnail generation?

**Comment by LukePulverenti** [comment]
Correct, it's built into the core now as the thumbnail generation feature that is part of library settings. The same throttle feature that we use for streaming could in theory be used for it as well.

**Comment by BernsteinA** [comment]
Thanks. I hope that does get implemented.
